name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Hoặc nhánh bạn muốn sử dụng

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: '3.10.4'  # Phiên bản Flutter của bạn

      - name: Install dependencies
        run: flutter pub get

      - name: Build the project
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
